# Generated by Django 6.0.6 on 2026-09-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_author_options_alter_book_options_and_more'),
        ('user_management', '0002_delivery_address_last_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'verbose_name': 'delivery address', 'verbose_name_plural': 'delivery addresses'},
        ),
        migrations.AlterModelOptions(
            name='lastview',
            options={'verbose_name': 'last view', 'verbose_name_plural': 'last views'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='branch',
            field=models.CharField(max_length=50, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='post_code',
            field=models.CharField(max_length=10, verbose_name='post code'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='state',
            field=models.CharField(max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='lastview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='lastview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
