# Generated by Django 6.0.6 on 2026-06-29 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('user_management', '0002_delivery_address_last_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Очікує'), ('PROCESSING', 'В обробці'), ('SHIPPED', 'Відправлено'), ('DELIVERED', 'Доставлено'), ('CANCELED', 'Скасовано')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Очікує'), ('PROCESSING', 'В обробці'), ('COMPLETED', 'Завершено'), ('FAILED', 'Помилка')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Готівка'), ('CARD', 'Картка'), ('ONLINE', 'Онлайн')], default='CARD', max_length=20)),
                ('ttn', models.CharField(blank=True, max_length=20)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.deliveryaddress')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
